# 预处理脚本，仅会在部署前运行一次
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-maibot-preprocessor
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-maibot-sa
      restartPolicy: Never
      containers:
        - name: preprocessor
          image: {{ .Values.pre_processor.image.repository | default "reg.mikumikumi.xyz/maibot/preprocessor" }}:{{ .Values.pre_processor.image.tag | default "0.12.1" }}
          imagePullPolicy: {{ .Values.pre_processor.image.pullPolicy }}
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: IS_WEBUI_ENABLED
              value: {{ .Values.core.webui.enabled | quote }}
            - name: IS_MMSG_ENABLED
              value: {{ .Values.core.maim_message_api_server.enabled | quote }}
            {{- if or .Values.config.override_adapter_config .Release.IsInstall }}
            - name: CONFIG_ADAPTER_B64
              value: {{ .Values.config.adapter_config | b64enc | quote }}
            {{- end }}
            - name: CONFIG_CORE_ENV_B64
              value: {{ tpl (.Files.Get "files/.env") . | b64enc | quote }}
            {{- if or .Values.config.override_core_bot_config .Release.IsInstall }}
            - name: CONFIG_CORE_BOT_B64
              value: {{ .Values.config.core_bot_config | b64enc | quote }}
            {{- end }}
            {{- if or .Values.config.override_core_model_config .Release.IsInstall }}
            - name: CONFIG_CORE_MODEL_B64
              value: {{ .Values.config.core_model_config | b64enc | quote }}
            {{- end }}
          volumeMounts:
            - mountPath: /app/config/adapter
              name: adapter-config
            - mountPath: /app/config/core
              name: core-config
      imagePullSecrets:
        {{ toYaml .Values.pre_processor.image.pullSecrets | nindent 8 }}
      {{- if .Values.pre_processor.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.pre_processor.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.pre_processor.tolerations }}
      tolerations:
        {{ toYaml .Values.pre_processor.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: adapter-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-maibot-adapter-config
        - name: core-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-maibot-core-config
